# Generated by Django 4.2.7 on 2025-03-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCTReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='oct_reports/')),
                ('min_gcl_ipl_od', models.FloatField(blank=True, null=True)),
                ('min_gcl_ipl_os', models.FloatField(blank=True, null=True)),
                ('avg_gcl_ipl_od', models.FloatField(blank=True, null=True)),
                ('avg_gcl_ipl_os', models.FloatField(blank=True, null=True)),
                ('rim_area_od', models.FloatField(blank=True, null=True)),
                ('rim_area_os', models.FloatField(blank=True, null=True)),
                ('vertical_cd_ratio_od', models.FloatField(blank=True, null=True)),
                ('vertical_cd_ratio_os', models.FloatField(blank=True, null=True)),
                ('glaucoma_prediction', models.CharField(blank=True, max_length=20, null=True)),
                ('heatmap_image', models.ImageField(blank=True, null=True, upload_to='heatmaps/')),
            ],
        ),
    ]
